"""工作台状态存取端口，由 bootstrap 注入 Redis 实现。"""
from __future__ import annotations
from typing import Protocol, Any
class WorkbenchStore(Protocol):
    # 限定工作台索引到可信 scope，项目和操作者之间不共享活动记录。
    def _scope_key(self, kind: str, scope_hash: str) -> Any: ...
    # 按 scope 和线程生成运行存储身份，与 runtime 的隔离方式保持一致。
    def _storage_id(self, scope_hash: str, thread_id: str) -> Any: ...
    # 为指定运行生成工作台元数据键，避免以展示名称作为存储身份。
    def _run_key(self, kind: str, scope_hash: str, thread_id: str) -> Any: ...
    # 将 Redis 字节值解码为文本，缺失值保留缺失语义。
    def _text(value: bytes | str | None) -> Any: ...
    # 把工作台元数据编码为稳定 JSON，仅接受上层筛选后的展示数据。
    def _dump(self, value: Any) -> Any: ...
    # 将已存 JSON 还原为工作台结构，解析失败不能冒充有效运行。
    def _load(self, payload: bytes) -> Any: ...
    # 原子预留 scope 内活动运行槽，防止并发创建或恢复启动多个互相冲突的运行。
    async def reserve_active(self, scope_hash: str, reservation_id: str) -> Any: ...
    # 把本次预留绑定到成功创建的线程，不能覆盖其他请求的预留。
    async def commit_active(self, scope_hash: str, reservation_id: str, thread_id: str) -> Any: ...
    # 只释放匹配本次预留或线程的活动槽，避免失败请求清掉另一运行。
    async def release_active(self, scope_hash: str, expected: str) -> Any: ...
    # 读取 scope 内当前活动线程，用于冲突提示而不代表工具正在执行。
    async def active_thread(self, scope_hash: str) -> Any: ...
    # 记录新运行的展示元数据和索引，使工作台能够按 scope 找回线程。
    async def register_run(self, scope_hash: str, thread_id: str, budget_preset: AgentBudgetPreset | str, created_at: datetime) -> Any: ...
    # 读取指定运行的展示元数据，不向调用方暴露 Redis 连接或 checkpoint 正文。
    async def run_metadata(self, scope_hash: str, thread_id: str) -> Any: ...
    # 返回 scope 下已登记线程列表，后续运行状态由服务层逐项核实。
    async def list_run_threads(self, scope_hash: str, *, limit: int=20, before: int | None=None) -> Any: ...
    # 保存步骤的脱敏证据投影，供工作台展示结果与保留策略。
    async def put_evidence(self, scope_hash: str, thread_id: str, evidence: AgentStepEvidence) -> Any: ...
    # 读取该运行的已登记步骤证据，不通过查询重新调用模型或工具。
    async def get_evidence(self, scope_hash: str, thread_id: str) -> Any: ...
    # 为同一运行定位事件序列和边界键，使追加与恢复共享游标空间。
    def _timeline_keys(self, scope_hash: str, thread_id: str, event_id: str) -> Any: ...
    # 追加有序工作台事件并维护有界历史，避免长期运行无限积累展示记录。
    async def append_timeline_event(self, scope_hash: str, thread_id: str, event_id: str, payload: dict[str, Any]) -> Any: ...
    # 从客户端游标恢复有界时间线，过期游标需按返回边界重新同步。
    async def replay_timeline(self, scope_hash: str, thread_id: str, after_sequence: int) -> Any: ...
    # 对重复或过密的进度更新进行接纳判断，减少时间线噪声。
    async def accept_progress(self, scope_hash: str, thread_id: str, step_stage: str, bucket: int) -> Any: ...
    # 返回当前可重放的时间线边界，供 SSE 判断历史是否已被截断。
    async def timeline_bounds(self, scope_hash: str, thread_id: str) -> Any: ...
    # 刷新普通消费 worker 的存活记录；验收用 no-consume 心跳不调用此接口。
    async def heartbeat_worker(self, consumer: str, *, ttl_seconds: int=30) -> Any: ...
    # 只依据正常 worker 存活标记判断可消费能力，独立验收心跳不能使其返回可用。
    async def worker_available(self) -> Any: ...
