from enum import Enum


# 保存的LLM对项目此前的分析信息的类型，即保存上下文信息
class InfoType(Enum):
    # 对整个项目的初步分析信息
    PROJECT_INITIAL_SUMMARY = 1
    PROJECT_UNITS_SUMMARY = 2
    PROJECT_UNIT_TEST_KNOWLEDGE = 3
    PROJECT_STATIC_BLACKBOX_KNOWLEDGE = 4
    PROJECT_STATIC_WHITEBOX_KNOWLEDGE = 5
    PROJECT_INTEGRATION_TEST_KNOWLEDGE = 6
    PROJECT_INTEGRATION_BIGBANG_KNOWLEDGE = 7
    PROJECT_INTEGRATION_TOP_DOWN_KNOWLEDGE = 8
    PROJECT_INTEGRATION_BOTTOM_UP_KNOWLEDGE = 9
    PROJECT_INTEGRATION_SANDWICH_KNOWLEDGE = 10
    PROJECT_APIS_SUMMARY = 11
    PROJECT_API_TEST_KNOWLEDGE = 12
    PROJECT_UI_SUMMARY = 13
    PROJECT_UI_TEST_KNOWLEDGE = 14
    PROJECT_DB_SUMMARY = 15
    PROJECT_DB_TEST_KNOWLEDGE = 16
    PROJECT_FUNCTIONAL_SUMMARY = 17
    PROJECT_FUNCTION_TEST_KNOWLEDGE = 18
    PROJECT_NONFUNCTIONAL_SUMMARY = 19
    PROJECT_ACCEPTANCE_SUMMARY = 20
    PROJECT_ACCEPTANCE_TEST_KNOWLEDGE = 21
    PROJECT_TEST_PLAN = 22
    PROJECT_TEST_MENU = 23
