# 共享稳定状态值与纯转换，具体业务状态迁移仍由所属域负责。
from enum import Enum


# 定义后端的状态码枚举(用4位数区分http状态码)
class Status(Enum):
    SUCCESS = 2001
    PROJECT_ADD_FAILURE = 5001
    PROJECT_INFO_FAILURE = 5002
    FILE_UPLOAD_FAILURE = 5901
    FILE_PATH_SAVE_FAILURE = 5902
    LOGIN_FAILURE = 5101
    LLM_MENU_ANALYSIS_FAILURE = 5201
    UNIT_INFO_GET_FAILURE = 5202
    INTEGRATION_INFO_GET_FAILURE = 5301
    LLM_APIS_ANALYSIS_FAILURE = 5401
