"""观测存取协议与安全错误类型，API 不导入 SQLite 实现。"""
from __future__ import annotations
from typing import Protocol, Any
class ObservabilityStorageError(RuntimeError):
    """A stable storage failure that never contains paths or database details."""


class ObservabilityStore(Protocol):
    # 返回 span 记录的容量约束，供写入前的批次和保留策略使用。
    def span_limit(self) -> Any: ...
    # 返回指标记录容量约束，不代表产品负载能力。
    def metric_limit(self) -> Any: ...
    # 返回脱敏日志记录容量约束，避免本地观测无限增长。
    def log_limit(self) -> Any: ...
    # 打开本地观测 SQLite 并初始化所需结构；应只由观测进程生命周期显式调用。
    def open(self) -> Any: ...
    # 创建观测专用表和索引，不操作项目 MySQL schema。
    def _create_schema(connection: sqlite3.Connection) -> Any: ...
    # 关闭本实例 SQLite 连接，生命周期结束后不再接受查询或写入。
    def close(self) -> Any: ...
    # 检查本实例是否已具备可用连接，不能代替产品数据库或普通 worker 的就绪状态。
    def ready(self) -> Any: ...
    # 要求观测连接已打开，未进入生命周期时明确失败而不隐式初始化。
    def _require(self) -> Any: ...
    # 将通过共享 wire schema 校验的脱敏 span 批次交给本地写入流程。
    def insert_spans(self, records: Iterable[SpanRecord]) -> Any: ...
    # 保存允许的指标记录，不接收任意业务字段或高基数标签。
    def insert_metrics(self, records: Iterable[MetricRecord]) -> Any: ...
    # 保存允许事件与字段组成的脱敏日志，不持久化异常正文或自由文本载荷。
    def insert_logs(self, records: Iterable[LogRecord]) -> Any: ...
    # 在本地连接和锁的约束下写入批次，并保持事务与清理边界。
    def _insert(self, statement: str, rows: list[tuple[Any, ...]]) -> Any: ...
    # 执行既定保留期和行数上限策略，仅作用于本地观测记录。
    def cleanup(self, *, now_ms: int | None=None) -> Any: ...
    # 按观测保留策略裁剪 trace/span 历史，不能把观测清理扩展为项目数据删除。
    def _trim_traces(self, connection: sqlite3.Connection) -> Any: ...
    # 对指定观测表保留有界记录，表选择来自实现白名单而非用户 SQL。
    def _trim_rows(connection: sqlite3.Connection, table: str, limit: int) -> Any: ...
    # 返回观测表计数供状态展示，不读取业务数据库。
    def counts(self) -> Any: ...
    # 按时间和筛选条件返回 trace 摘要，详情通过独立查询获取。
    def trace_summaries(self, *, since_ms: int, status: str | None, limit: int, before: int | None) -> Any: ...
    # 读取指定 trace 的观测结构；该接口不重放原始模型或工具调用。
    def trace_detail(self, trace_id: str) -> Any: ...
    # 在有界筛选窗口内读取脱敏日志，禁止任意 SQL 或自由字段查询。
    def logs(self, *, since_ms: int, level: str | None, service: str | None, limit: int, before: int | None) -> Any: ...
    # 读取窗口内指标供纯聚合函数计算，不访问外部监控服务。
    def metrics_since(self, since_ms: int) -> Any: ...
